/*
  Copyright (c) 2007-2014 Red Hat, Inc. <http://www.redhat.com>
  This file is part of GlusterFS.

  This file is licensed to you under your choice of the GNU Lesser
  General Public License, version 3 or any later version (LGPLv3 or
  later), or the GNU General Public License, version 2 (GPLv2), in all
  cases as published by the Free Software Foundation.
*/

#include "compat.h"
#include "xdr-common.h"
#include "xdr-nfs3.h"

#if defined(__GNUC__)
#if __GNUC__ >= 4
#if !defined(__clang__)
#if !defined(__NetBSD__)
#pragma GCC diagnostic ignored "-Wunused-but-set-variable"
#pragma GCC diagnostic ignored "-Wunused-variable"
#endif
#else
#pragma clang diagnostic ignored "-Wunused-variable"
#pragma clang diagnostic ignored "-Wunused-value"
#endif
#endif
#endif

/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "../../../rpc/xdr/src/changelog-xdr.h"

bool_t
xdr_changelog_probe_req (XDR *xdrs, changelog_probe_req *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_u_int (xdrs, &objp->filter))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->sock, UNIX_PATH_MAX,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_changelog_probe_rsp (XDR *xdrs, changelog_probe_rsp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->op_ret))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_changelog_event_req (XDR *xdrs, changelog_event_req *objp)
{
	register int32_t *buf;

	 if (!xdr_u_long (xdrs, &objp->seq))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->tv_sec))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->tv_usec))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_changelog_event_rsp (XDR *xdrs, changelog_event_rsp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->op_ret))
		 return FALSE;
	 if (!xdr_u_long (xdrs, &objp->seq))
		 return FALSE;
	return TRUE;
}
